#!/bin/bash
#
# Copyright (C) 2013 MORITA Kazutaka <morita.kazutaka@gmail.com>
#

. git-qsh-setup

USAGE="[<patch>]"

name=$1
if [ "$name" = "" ]; then
    name=$(git qnext)
fi

setup_colors()
{
	local C=diff_hdr=32:diff_add=36:diff_mod=35:diff_rem=35:diff_hunk=33:diff_ctx=35:diff_cctx=33:patch_offs=33:patch_fuzz=35:patch_fail=31:patch_applied=32:clear=00
	[ -n "$QUILT_COLORS" ] && C="$C:$QUILT_COLORS"

	C=${C//=/=\'$'\e'[}
	C=color_${C//:/m\'; color_}m\'
	eval $C
}

colorize()
{
    setup_colors
    sed -e '
	    s/^\(Index:\|---\|+++\|\*\*\*\) .*/'$color_diff_hdr'&'$color_clear'/
	t ; s/^+.*/'$color_diff_add'&'$color_clear'/
	t ; s/^-.*/'$color_diff_rem'&'$color_clear'/
	t ; s/^!.*/'$color_diff_mod'&'$color_clear'/
	t ; s/^\(@@ \-[0-9]\+\(,[0-9]\+\)\? +[0-9]\+\(,[0-9]\+\)\? @@\)\([ \t]*\)\(.*\)/'$color_diff_hunk'\1'$color_clear'\4'$color_diff_ctx'\5'$color_clear'/
	t ; s/^\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*.*/'$color_diff_cctx'&'$color_clear'/
	'
}

_filter()
{
    sed ':loop; N; $!b loop; ;s/\n\t/,/g' | \
	perl -pe '
if ($commitlog) {
} elsif ($body) {
    if (/^--/) {
        $commitlog = 1
    } elsif ($_) {
        $_ = "    $_";
    }
} else {
    if (/^\n$/) {
        $body = 1;
    } elsif (/^Subject: (\[.+?\] ?)*(.+)/) {
        $_ = "\n    $2\n";
    } elsif (/^Date:/) {
    } elsif (/^From:(.+)/) {
        $_ = "Author:$1\n";
    } else {
        $_ = "";
    }
}
'
}

if [ -t 1 ]; then
    cat $GITQ_DIR/$branch/$name | _filter | colorize | $pager
else
    cat $GITQ_DIR/$branch/$name | _filter
fi
