#!/bin/bash
#
# Copyright (C) 2013 MORITA Kazutaka <morita.kazutaka@gmail.com>
#
# This code is based on guilt-series from Guilt (Git Quilt):
#   Copyright (c) Josef "Jeff" Sipek, 2006-2011
#

. git-qsh-setup

USAGE="[-v | -e]"

while case "$#" in 0) break ;; esac
do
    case "$1" in
	-v)
	    verbose=t ;;
	-e)
	    edit=t ;;
	*)
	    usage ;;
    esac
    shift
done

if [ ! -z "$edit" ]; then 
    git_editor "$series"
elif [ -z "$verbose" ]; then
    cat "$series"
else
    prefix="+"
    top=`get_top`

    for patch in `cat "$series"`; do 
	if [ -z "$top" ]; then
	    echo "  $patch"
	else
	    if [ "$patch" = "$top" ]; then
		echo "= $patch"
		prefix=" "
	    else
		echo "$prefix $patch"
	    fi
	fi
    done
fi

# cleanup unused patches
for f in $GITQ_DIR/$branch/*; do
    if [ $f = "$series" -o $f = "$applied" ]; then
	continue
    fi
    if ! grep -q "^`basename $f`$" "$series"; then
	rm $f
    fi
done
