#!/bin/bash
#
# Copyright (C) 2013 MORITA Kazutaka <morita.kazutaka@gmail.com>
#

. git-qsh-setup

USAGE="<commit>"

if [ $# -ne 1 ] || [ -z "$1" ]; then
    usage
fi

commit="$1"

if ! must_commit_first; then
    die "Uncommited changes detected."
fi

DIR=$(mktemp -d)

git format-patch -o $DIR --quiet $commit

TMP=$(mktemp)
cp "$series" $TMP
truncate -s 0 "$series"
git qimport $DIR/* && git reset $commit --hard
cat $TMP >> "$series"
rm $TMP

rm -r $DIR
