#!/bin/bash
#
# Copyright (C) 2013 MORITA Kazutaka <morita.kazutaka@gmail.com>
#
# This code is based on guilt-unapplied from Guilt (Git Quilt):
#   Copyright (c) Josef "Jeff" Sipek, 2006-2011
#

. git-qsh-setup

USAGE=""

if [ $# -ne 0 ]; then
	usage
fi

n=`wc -l < "$applied"`
n=`expr $n + 1`

sed -n -e "$n,\$p" "$series"
