#!/bin/bash
#
# Copyright (C) 2013 MORITA Kazutaka <morita.kazutaka@gmail.com>
#

. git-qsh-setup

USAGE="<src> <dst>"

src=$1
dst=$2

if [ "$dst" = "" ]; then
    usage
fi

if [ ! -e "$GITQ_DIR/$branch/$src" ]; then
    die "no such patch: $src"
fi

if [ -e "$GITQ_DIR/$branch/$dst" ]; then
    die "already exists: $dst"
fi

mv "$GITQ_DIR/$branch/$src" "$GITQ_DIR/$branch/$dst"
sed -i s/$src/$dst/ "$series"
