#!/bin/bash
#
# Copyright (C) 2013 MORITA Kazutaka <morita.kazutaka@gmail.com>
#
# This code is based on guilt-applied from Guilt (Git Quilt):
#   Copyright (c) Josef "Jeff" Sipek, 2006-2011
#

. git-qsh-setup

USAGE="[-c]"

case $# in
    0)
	# just output the regular series-style applied list
	cat "$applied"
	;;

    1)
	if [ "$1" != "-c" ]; then
	    usage
	fi

	for pname in $(cat "$applied"); do
	    git show-ref refs/patches/$branch/$pname | sed -e "s,refs/patches/$branch/,,"
	done
	;;

    *)
	usage
	;;
esac
