#!/bin/bash
#
# Copyright (C) 2013 MORITA Kazutaka <morita.kazutaka@gmail.com>
#

. git-qsh-setup

USAGE="[<hash> | <since>..[<until>] | ..<until>]"

if [ $# -ne 1 ] || [ -z "$1" ]; then
    usage
fi

rhash=`munge_hash_range $1`

# make sure that there are no unapplied changes
if ! must_commit_first; then
    die "Uncommited changes detected."
fi

DIR=$(mktemp -d)
git format-patch -o $DIR --quiet $rhash
git qimport $DIR/*
rm -r $DIR
